sudo: required
services:
  - docker

before_install:
  - docker build -t ryanashneil/docker-react -f dev.Dockerfile .

script:
  - docker run ryanashneil/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "dev-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-243171680554"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"