version: '3'

services: 
  react-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  react-tests:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
       - /app/node_modules
       - .:/app
    command: ["npm", "run", "test"]